"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: adapters
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from api_client_adapters.api_client import ApiClient, Endpoint as _Endpoint
from api_client_adapters.model_utils import (  # noqa: F401
    check_allowed_values,
    check_validations,
    date,
    datetime,
    file_type,
    none_type,
    validate_and_convert_types
)
from api_client_adapters.model.adapters_auto_tests_id_work_items_post_request import AdaptersAutoTestsIdWorkItemsPostRequest
from api_client_adapters.model.adapters_auto_tests_post_request import AdaptersAutoTestsPostRequest
from api_client_adapters.model.adapters_auto_tests_put_request import AdaptersAutoTestsPutRequest
from api_client_adapters.model.adapters_auto_tests_search_post_request import AdaptersAutoTestsSearchPostRequest
from api_client_adapters.model.auto_test_api_result import AutoTestApiResult
from api_client_adapters.model.auto_test_create_api_model import AutoTestCreateApiModel
from api_client_adapters.model.auto_test_model import AutoTestModel
from api_client_adapters.model.auto_test_update_api_model import AutoTestUpdateApiModel
from api_client_adapters.model.auto_test_work_item_identifier_api_result import AutoTestWorkItemIdentifierApiResult
from api_client_adapters.model.operation import Operation
from api_client_adapters.model.problem_details import ProblemDetails
from api_client_adapters.model.validation_problem_details import ValidationProblemDetails


class AutoTestsApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client
        self.adapters_auto_tests_bulk_post_endpoint = _Endpoint(
            settings={
                'response_type': ([AutoTestApiResult],),
                'auth': [
                    'PrivateToken',
                    'Cookies'
                ],
                'endpoint_path': '/adapters/autoTests/bulk',
                'operation_id': 'adapters_auto_tests_bulk_post',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'auto_test_create_api_model',
                ],
                'required': [],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                    'auto_test_create_api_model',
                ]
            },
            root_map={
                'validations': {
                    ('auto_test_create_api_model',): {

                        'min_items': 1,
                    },
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'auto_test_create_api_model':
                        ([AutoTestCreateApiModel],),
                },
                'attribute_map': {
                },
                'location_map': {
                    'auto_test_create_api_model': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client
        )
        self.adapters_auto_tests_bulk_put_endpoint = _Endpoint(
            settings={
                'response_type': None,
                'auth': [
                    'PrivateToken',
                    'Cookies'
                ],
                'endpoint_path': '/adapters/autoTests/bulk',
                'operation_id': 'adapters_auto_tests_bulk_put',
                'http_method': 'PUT',
                'servers': None,
            },
            params_map={
                'all': [
                    'auto_test_update_api_model',
                ],
                'required': [],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'auto_test_update_api_model':
                        ([AutoTestUpdateApiModel],),
                },
                'attribute_map': {
                },
                'location_map': {
                    'auto_test_update_api_model': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client
        )
        self.adapters_auto_tests_get_endpoint = _Endpoint(
            settings={
                'response_type': ([AutoTestModel],),
                'auth': [
                    'PrivateToken',
                    'Cookies'
                ],
                'endpoint_path': '/adapters/autoTests',
                'operation_id': 'adapters_auto_tests_get',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'project_id',
                    'external_id',
                    'global_id',
                    'namespace',
                    'is_namespace_null',
                    'include_empty_namespaces',
                    'class_name',
                    'is_classname_null',
                    'include_empty_class_names',
                    'is_deleted',
                    'deleted',
                    'labels',
                    'stability_minimal',
                    'min_stability',
                    'stability_maximal',
                    'max_stability',
                    'is_flaky',
                    'flaky',
                    'include_steps',
                    'include_labels',
                    'external_key',
                    'skip',
                    'take',
                    'order_by',
                    'search_field',
                    'search_value',
                ],
                'required': [],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'project_id':
                        (str,),
                    'external_id':
                        (str,),
                    'global_id':
                        (int,),
                    'namespace':
                        (str,),
                    'is_namespace_null':
                        (bool,),
                    'include_empty_namespaces':
                        (bool,),
                    'class_name':
                        (str,),
                    'is_classname_null':
                        (bool,),
                    'include_empty_class_names':
                        (bool,),
                    'is_deleted':
                        (bool,),
                    'deleted':
                        (bool,),
                    'labels':
                        ([str],),
                    'stability_minimal':
                        (int,),
                    'min_stability':
                        (int,),
                    'stability_maximal':
                        (int,),
                    'max_stability':
                        (int,),
                    'is_flaky':
                        (bool,),
                    'flaky':
                        (bool,),
                    'include_steps':
                        (bool,),
                    'include_labels':
                        (bool,),
                    'external_key':
                        (str,),
                    'skip':
                        (int,),
                    'take':
                        (int,),
                    'order_by':
                        (str,),
                    'search_field':
                        (str,),
                    'search_value':
                        (str,),
                },
                'attribute_map': {
                    'project_id': 'projectId',
                    'external_id': 'externalId',
                    'global_id': 'globalId',
                    'namespace': 'namespace',
                    'is_namespace_null': 'isNamespaceNull',
                    'include_empty_namespaces': 'includeEmptyNamespaces',
                    'class_name': 'className',
                    'is_classname_null': 'isClassnameNull',
                    'include_empty_class_names': 'includeEmptyClassNames',
                    'is_deleted': 'isDeleted',
                    'deleted': 'deleted',
                    'labels': 'labels',
                    'stability_minimal': 'stabilityMinimal',
                    'min_stability': 'minStability',
                    'stability_maximal': 'stabilityMaximal',
                    'max_stability': 'maxStability',
                    'is_flaky': 'isFlaky',
                    'flaky': 'flaky',
                    'include_steps': 'includeSteps',
                    'include_labels': 'includeLabels',
                    'external_key': 'externalKey',
                    'skip': 'Skip',
                    'take': 'Take',
                    'order_by': 'OrderBy',
                    'search_field': 'SearchField',
                    'search_value': 'SearchValue',
                },
                'location_map': {
                    'project_id': 'query',
                    'external_id': 'query',
                    'global_id': 'query',
                    'namespace': 'query',
                    'is_namespace_null': 'query',
                    'include_empty_namespaces': 'query',
                    'class_name': 'query',
                    'is_classname_null': 'query',
                    'include_empty_class_names': 'query',
                    'is_deleted': 'query',
                    'deleted': 'query',
                    'labels': 'query',
                    'stability_minimal': 'query',
                    'min_stability': 'query',
                    'stability_maximal': 'query',
                    'max_stability': 'query',
                    'is_flaky': 'query',
                    'flaky': 'query',
                    'include_steps': 'query',
                    'include_labels': 'query',
                    'external_key': 'query',
                    'skip': 'query',
                    'take': 'query',
                    'order_by': 'query',
                    'search_field': 'query',
                    'search_value': 'query',
                },
                'collection_format_map': {
                    'labels': 'multi',
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client
        )
        self.adapters_auto_tests_id_get_endpoint = _Endpoint(
            settings={
                'response_type': (AutoTestApiResult,),
                'auth': [
                    'PrivateToken',
                    'Cookies'
                ],
                'endpoint_path': '/adapters/autoTests/{id}',
                'operation_id': 'adapters_auto_tests_id_get',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'id',
                ],
                'required': [
                    'id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'id':
                        (str,),
                },
                'attribute_map': {
                    'id': 'id',
                },
                'location_map': {
                    'id': 'path',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client
        )
        self.adapters_auto_tests_id_patch_endpoint = _Endpoint(
            settings={
                'response_type': None,
                'auth': [
                    'PrivateToken',
                    'Cookies'
                ],
                'endpoint_path': '/adapters/autoTests/{id}',
                'operation_id': 'adapters_auto_tests_id_patch',
                'http_method': 'PATCH',
                'servers': None,
            },
            params_map={
                'all': [
                    'id',
                    'operation',
                ],
                'required': [
                    'id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'id':
                        (str,),
                    'operation':
                        ([Operation],),
                },
                'attribute_map': {
                    'id': 'id',
                },
                'location_map': {
                    'id': 'path',
                    'operation': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client
        )
        self.adapters_auto_tests_id_work_items_delete_endpoint = _Endpoint(
            settings={
                'response_type': None,
                'auth': [
                    'PrivateToken',
                    'Cookies'
                ],
                'endpoint_path': '/adapters/autoTests/{id}/work-items',
                'operation_id': 'adapters_auto_tests_id_work_items_delete',
                'http_method': 'DELETE',
                'servers': None,
            },
            params_map={
                'all': [
                    'id',
                    'work_item_id',
                ],
                'required': [
                    'id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'id':
                        (str,),
                    'work_item_id':
                        (str,),
                },
                'attribute_map': {
                    'id': 'id',
                    'work_item_id': 'workItemId',
                },
                'location_map': {
                    'id': 'path',
                    'work_item_id': 'query',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client
        )
        self.adapters_auto_tests_id_work_items_get_endpoint = _Endpoint(
            settings={
                'response_type': ([AutoTestWorkItemIdentifierApiResult],),
                'auth': [
                    'PrivateToken',
                    'Cookies'
                ],
                'endpoint_path': '/adapters/autoTests/{id}/work-items',
                'operation_id': 'adapters_auto_tests_id_work_items_get',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'id',
                    'is_deleted',
                    'is_work_item_deleted',
                ],
                'required': [
                    'id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'id':
                        (str,),
                    'is_deleted':
                        (bool,),
                    'is_work_item_deleted':
                        (bool,),
                },
                'attribute_map': {
                    'id': 'id',
                    'is_deleted': 'isDeleted',
                    'is_work_item_deleted': 'isWorkItemDeleted',
                },
                'location_map': {
                    'id': 'path',
                    'is_deleted': 'query',
                    'is_work_item_deleted': 'query',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client
        )
        self.adapters_auto_tests_id_work_items_post_endpoint = _Endpoint(
            settings={
                'response_type': None,
                'auth': [
                    'PrivateToken',
                    'Cookies'
                ],
                'endpoint_path': '/adapters/autoTests/{id}/work-items',
                'operation_id': 'adapters_auto_tests_id_work_items_post',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'id',
                    'adapters_auto_tests_id_work_items_post_request',
                ],
                'required': [
                    'id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'id':
                        (str,),
                    'adapters_auto_tests_id_work_items_post_request':
                        (AdaptersAutoTestsIdWorkItemsPostRequest,),
                },
                'attribute_map': {
                    'id': 'id',
                },
                'location_map': {
                    'id': 'path',
                    'adapters_auto_tests_id_work_items_post_request': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client
        )
        self.adapters_auto_tests_post_endpoint = _Endpoint(
            settings={
                'response_type': (AutoTestApiResult,),
                'auth': [
                    'PrivateToken',
                    'Cookies'
                ],
                'endpoint_path': '/adapters/autoTests',
                'operation_id': 'adapters_auto_tests_post',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'adapters_auto_tests_post_request',
                ],
                'required': [],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'adapters_auto_tests_post_request':
                        (AdaptersAutoTestsPostRequest,),
                },
                'attribute_map': {
                },
                'location_map': {
                    'adapters_auto_tests_post_request': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client
        )
        self.adapters_auto_tests_put_endpoint = _Endpoint(
            settings={
                'response_type': None,
                'auth': [
                    'PrivateToken',
                    'Cookies'
                ],
                'endpoint_path': '/adapters/autoTests',
                'operation_id': 'adapters_auto_tests_put',
                'http_method': 'PUT',
                'servers': None,
            },
            params_map={
                'all': [
                    'adapters_auto_tests_put_request',
                ],
                'required': [],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'adapters_auto_tests_put_request':
                        (AdaptersAutoTestsPutRequest,),
                },
                'attribute_map': {
                },
                'location_map': {
                    'adapters_auto_tests_put_request': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client
        )
        self.adapters_auto_tests_search_post_endpoint = _Endpoint(
            settings={
                'response_type': ([AutoTestApiResult],),
                'auth': [
                    'PrivateToken',
                    'Cookies'
                ],
                'endpoint_path': '/adapters/autoTests/search',
                'operation_id': 'adapters_auto_tests_search_post',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'skip',
                    'take',
                    'order_by',
                    'search_field',
                    'search_value',
                    'adapters_auto_tests_search_post_request',
                ],
                'required': [],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'skip':
                        (int,),
                    'take':
                        (int,),
                    'order_by':
                        (str,),
                    'search_field':
                        (str,),
                    'search_value':
                        (str,),
                    'adapters_auto_tests_search_post_request':
                        (AdaptersAutoTestsSearchPostRequest,),
                },
                'attribute_map': {
                    'skip': 'Skip',
                    'take': 'Take',
                    'order_by': 'OrderBy',
                    'search_field': 'SearchField',
                    'search_value': 'SearchValue',
                },
                'location_map': {
                    'skip': 'query',
                    'take': 'query',
                    'order_by': 'query',
                    'search_field': 'query',
                    'search_value': 'query',
                    'adapters_auto_tests_search_post_request': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client
        )

    def adapters_auto_tests_bulk_post(
        self,
        **kwargs
    ):
        """Create multiple autotests  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.adapters_auto_tests_bulk_post(async_req=True)
        >>> result = thread.get()


        Keyword Args:
            auto_test_create_api_model ([AutoTestCreateApiModel]): [optional]
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            _request_auths (list): set to override the auth_settings for an a single
                request; this effectively ignores the authentication
                in the spec for a single request.
                Default is None
            async_req (bool): execute request asynchronously

        Returns:
            [AutoTestApiResult]
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['_request_auths'] = kwargs.get('_request_auths', None)
        return self.adapters_auto_tests_bulk_post_endpoint.call_with_http_info(**kwargs)

    def adapters_auto_tests_bulk_put(
        self,
        **kwargs
    ):
        """Update multiple autotests  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.adapters_auto_tests_bulk_put(async_req=True)
        >>> result = thread.get()


        Keyword Args:
            auto_test_update_api_model ([AutoTestUpdateApiModel]): [optional]
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            _request_auths (list): set to override the auth_settings for an a single
                request; this effectively ignores the authentication
                in the spec for a single request.
                Default is None
            async_req (bool): execute request asynchronously

        Returns:
            None
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['_request_auths'] = kwargs.get('_request_auths', None)
        return self.adapters_auto_tests_bulk_put_endpoint.call_with_http_info(**kwargs)

    def adapters_auto_tests_get(
        self,
        **kwargs
    ):
        """adapters_auto_tests_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.adapters_auto_tests_get(async_req=True)
        >>> result = thread.get()


        Keyword Args:
            project_id (str): Project internal ID. [optional]
            external_id (str): Autotest external ID. [optional]
            global_id (int): Autotest global ID. [optional]
            namespace (str): Namespace in which autotest is located. [optional]
            is_namespace_null (bool): OBSOLETE: Use `includeEmptyNamespaces` instead. [optional]
            include_empty_namespaces (bool): If result must contain autotests without namespace. [optional]
            class_name (str): Name of class in which autotest is located. [optional]
            is_classname_null (bool): OBSOLETE: Use `includeEmptyClassNames` instead. [optional]
            include_empty_class_names (bool): If result must contain autotests without class. [optional]
            is_deleted (bool): OBSOLETE: Use `deleted` instead. [optional]
            deleted (bool): Is autotest deleted. [optional]
            labels ([str]): Include only autotests with provided labels. [optional]
            stability_minimal (int): OBSOLETE: Use `minStability` instead. [optional]
            min_stability (int): Minimum stability value of autotest. [optional]
            stability_maximal (int): OBSOLETE: Use `maxStability` instead. [optional]
            max_stability (int): Maximum stability value of autotest. [optional]
            is_flaky (bool): OBSOLETE: Use `flaky` instead. [optional]
            flaky (bool): Is autotest marked as \"Flaky\". [optional]
            include_steps (bool): If result must also include autotest steps. [optional]
            include_labels (bool): If result must also include autotest labels. [optional]
            external_key (str): External key of autotest. [optional]
            skip (int): Amount of items to be skipped (offset). [optional]
            take (int): Amount of items to be taken (limit). [optional]
            order_by (str): SQL-like  ORDER BY statement (column1 ASC|DESC , column2 ASC|DESC). [optional]
            search_field (str): Property name for searching. [optional]
            search_value (str): Value for searching. [optional]
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            _request_auths (list): set to override the auth_settings for an a single
                request; this effectively ignores the authentication
                in the spec for a single request.
                Default is None
            async_req (bool): execute request asynchronously

        Returns:
            [AutoTestModel]
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['_request_auths'] = kwargs.get('_request_auths', None)
        return self.adapters_auto_tests_get_endpoint.call_with_http_info(**kwargs)

    def adapters_auto_tests_id_get(
        self,
        id,
        **kwargs
    ):
        """Get autotest by internal or global ID  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.adapters_auto_tests_id_get(id, async_req=True)
        >>> result = thread.get()

        Args:
            id (str): Internal (UUID) or global (integer) identifier

        Keyword Args:
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            _request_auths (list): set to override the auth_settings for an a single
                request; this effectively ignores the authentication
                in the spec for a single request.
                Default is None
            async_req (bool): execute request asynchronously

        Returns:
            AutoTestApiResult
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['_request_auths'] = kwargs.get('_request_auths', None)
        kwargs['id'] = \
            id
        return self.adapters_auto_tests_id_get_endpoint.call_with_http_info(**kwargs)

    def adapters_auto_tests_id_patch(
        self,
        id,
        **kwargs
    ):
        """Patch auto test  # noqa: E501

        See <a href=\"https://www.rfc-editor.org/rfc/rfc6902\" target=\"_blank\">RFC 6902: JavaScript Object Notation (JSON) Patch</a> for details  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.adapters_auto_tests_id_patch(id, async_req=True)
        >>> result = thread.get()

        Args:
            id (str):

        Keyword Args:
            operation ([Operation]): [optional]
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            _request_auths (list): set to override the auth_settings for an a single
                request; this effectively ignores the authentication
                in the spec for a single request.
                Default is None
            async_req (bool): execute request asynchronously

        Returns:
            None
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['_request_auths'] = kwargs.get('_request_auths', None)
        kwargs['id'] = \
            id
        return self.adapters_auto_tests_id_patch_endpoint.call_with_http_info(**kwargs)

    def adapters_auto_tests_id_work_items_delete(
        self,
        id,
        **kwargs
    ):
        """Unlink autotest from work item  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.adapters_auto_tests_id_work_items_delete(id, async_req=True)
        >>> result = thread.get()

        Args:
            id (str): Internal (UUID) or global (integer) identifier

        Keyword Args:
            work_item_id (str): Internal (UUID) or global (integer) identifier. [optional]
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            _request_auths (list): set to override the auth_settings for an a single
                request; this effectively ignores the authentication
                in the spec for a single request.
                Default is None
            async_req (bool): execute request asynchronously

        Returns:
            None
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['_request_auths'] = kwargs.get('_request_auths', None)
        kwargs['id'] = \
            id
        return self.adapters_auto_tests_id_work_items_delete_endpoint.call_with_http_info(**kwargs)

    def adapters_auto_tests_id_work_items_get(
        self,
        id,
        **kwargs
    ):
        """Get work items linked to autotest  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.adapters_auto_tests_id_work_items_get(id, async_req=True)
        >>> result = thread.get()

        Args:
            id (str): Internal (UUID) or global (integer) identifier

        Keyword Args:
            is_deleted (bool): [optional]
            is_work_item_deleted (bool): [optional] if omitted the server will use the default value of False
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            _request_auths (list): set to override the auth_settings for an a single
                request; this effectively ignores the authentication
                in the spec for a single request.
                Default is None
            async_req (bool): execute request asynchronously

        Returns:
            [AutoTestWorkItemIdentifierApiResult]
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['_request_auths'] = kwargs.get('_request_auths', None)
        kwargs['id'] = \
            id
        return self.adapters_auto_tests_id_work_items_get_endpoint.call_with_http_info(**kwargs)

    def adapters_auto_tests_id_work_items_post(
        self,
        id,
        **kwargs
    ):
        """Link autotest with work items  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.adapters_auto_tests_id_work_items_post(id, async_req=True)
        >>> result = thread.get()

        Args:
            id (str): Internal (UUID) or global (integer) identifier

        Keyword Args:
            adapters_auto_tests_id_work_items_post_request (AdaptersAutoTestsIdWorkItemsPostRequest): [optional]
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            _request_auths (list): set to override the auth_settings for an a single
                request; this effectively ignores the authentication
                in the spec for a single request.
                Default is None
            async_req (bool): execute request asynchronously

        Returns:
            None
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['_request_auths'] = kwargs.get('_request_auths', None)
        kwargs['id'] = \
            id
        return self.adapters_auto_tests_id_work_items_post_endpoint.call_with_http_info(**kwargs)

    def adapters_auto_tests_post(
        self,
        **kwargs
    ):
        """Create autotest  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.adapters_auto_tests_post(async_req=True)
        >>> result = thread.get()


        Keyword Args:
            adapters_auto_tests_post_request (AdaptersAutoTestsPostRequest): [optional]
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            _request_auths (list): set to override the auth_settings for an a single
                request; this effectively ignores the authentication
                in the spec for a single request.
                Default is None
            async_req (bool): execute request asynchronously

        Returns:
            AutoTestApiResult
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['_request_auths'] = kwargs.get('_request_auths', None)
        return self.adapters_auto_tests_post_endpoint.call_with_http_info(**kwargs)

    def adapters_auto_tests_put(
        self,
        **kwargs
    ):
        """Update autotest  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.adapters_auto_tests_put(async_req=True)
        >>> result = thread.get()


        Keyword Args:
            adapters_auto_tests_put_request (AdaptersAutoTestsPutRequest): [optional]
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            _request_auths (list): set to override the auth_settings for an a single
                request; this effectively ignores the authentication
                in the spec for a single request.
                Default is None
            async_req (bool): execute request asynchronously

        Returns:
            None
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['_request_auths'] = kwargs.get('_request_auths', None)
        return self.adapters_auto_tests_put_endpoint.call_with_http_info(**kwargs)

    def adapters_auto_tests_search_post(
        self,
        **kwargs
    ):
        """Search for autotests  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.adapters_auto_tests_search_post(async_req=True)
        >>> result = thread.get()


        Keyword Args:
            skip (int): Amount of items to be skipped (offset). [optional]
            take (int): Amount of items to be taken (limit). [optional]
            order_by (str): SQL-like  ORDER BY statement (column1 ASC|DESC , column2 ASC|DESC). [optional]
            search_field (str): Property name for searching. [optional]
            search_value (str): Value for searching. [optional]
            adapters_auto_tests_search_post_request (AdaptersAutoTestsSearchPostRequest): [optional]
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            _request_auths (list): set to override the auth_settings for an a single
                request; this effectively ignores the authentication
                in the spec for a single request.
                Default is None
            async_req (bool): execute request asynchronously

        Returns:
            [AutoTestApiResult]
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['_request_auths'] = kwargs.get('_request_auths', None)
        return self.adapters_auto_tests_search_post_endpoint.call_with_http_info(**kwargs)

