# flake8: noqa

"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: adapters
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from adapters_api.api_client import ApiClient

# import Configuration
from adapters_api.configuration import Configuration

# import exceptions
from adapters_api.exceptions import OpenApiException
from adapters_api.exceptions import ApiAttributeError
from adapters_api.exceptions import ApiTypeError
from adapters_api.exceptions import ApiValueError
from adapters_api.exceptions import ApiKeyError
from adapters_api.exceptions import ApiException
