"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: adapters
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from api_client_adapters.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from api_client_adapters.exceptions import ApiAttributeError


def lazy_import():
    from api_client_adapters.model.work_item_filter_api_model import WorkItemFilterApiModel
    from api_client_adapters.model.work_item_filter_api_model_duration import WorkItemFilterApiModelDuration
    from api_client_adapters.model.work_item_priority_model import WorkItemPriorityModel
    from api_client_adapters.model.work_item_source_type_model import WorkItemSourceTypeModel
    from api_client_adapters.model.work_item_states import WorkItemStates
    from api_client_adapters.model.work_item_type_model import WorkItemTypeModel
    globals()['WorkItemFilterApiModel'] = WorkItemFilterApiModel
    globals()['WorkItemFilterApiModelDuration'] = WorkItemFilterApiModelDuration
    globals()['WorkItemPriorityModel'] = WorkItemPriorityModel
    globals()['WorkItemSourceTypeModel'] = WorkItemSourceTypeModel
    globals()['WorkItemStates'] = WorkItemStates
    globals()['WorkItemTypeModel'] = WorkItemTypeModel


class WorkItemSelectApiModelFilter(ModelComposed):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
        ('include_ids',): {
        },
        ('exclude_ids',): {
        },
        ('project_ids',): {
        },
        ('name',): {
            'max_length': 255,
            'min_length': 0,
        },
        ('ids',): {
        },
        ('global_ids',): {
        },
        ('section_ids',): {
        },
        ('states',): {
        },
        ('priorities',): {
        },
        ('source_types',): {
        },
        ('types',): {
        },
        ('tags',): {
        },
        ('exclude_tags',): {
        },
        ('auto_test_ids',): {
        },
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'name_or_id': (str, none_type,),  # noqa: E501
            'include_ids': ([str], none_type,),  # noqa: E501
            'exclude_ids': ([str], none_type,),  # noqa: E501
            'project_ids': ([str], none_type,),  # noqa: E501
            'name': (str, none_type,),  # noqa: E501
            'ids': ([str], none_type,),  # noqa: E501
            'global_ids': ([int], none_type,),  # noqa: E501
            'attributes': ({str: ([str], none_type)}, none_type,),  # noqa: E501
            'is_deleted': (bool, none_type,),  # noqa: E501
            'section_ids': ([str], none_type,),  # noqa: E501
            'states': ([WorkItemStates], none_type,),  # noqa: E501
            'priorities': ([WorkItemPriorityModel], none_type,),  # noqa: E501
            'source_types': ([WorkItemSourceTypeModel], none_type,),  # noqa: E501
            'types': ([WorkItemTypeModel], none_type,),  # noqa: E501
            'duration': (WorkItemFilterApiModelDuration,),  # noqa: E501
            'is_automated': (bool, none_type,),  # noqa: E501
            'tags': ([str], none_type,),  # noqa: E501
            'exclude_tags': ([str], none_type,),  # noqa: E501
            'auto_test_ids': ([str], none_type,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'name_or_id': 'nameOrId',  # noqa: E501
        'include_ids': 'includeIds',  # noqa: E501
        'exclude_ids': 'excludeIds',  # noqa: E501
        'project_ids': 'projectIds',  # noqa: E501
        'name': 'name',  # noqa: E501
        'ids': 'ids',  # noqa: E501
        'global_ids': 'globalIds',  # noqa: E501
        'attributes': 'attributes',  # noqa: E501
        'is_deleted': 'isDeleted',  # noqa: E501
        'section_ids': 'sectionIds',  # noqa: E501
        'states': 'states',  # noqa: E501
        'priorities': 'priorities',  # noqa: E501
        'source_types': 'sourceTypes',  # noqa: E501
        'types': 'types',  # noqa: E501
        'duration': 'duration',  # noqa: E501
        'is_automated': 'isAutomated',  # noqa: E501
        'tags': 'tags',  # noqa: E501
        'exclude_tags': 'excludeTags',  # noqa: E501
        'auto_test_ids': 'autoTestIds',  # noqa: E501
    }

    read_only_vars = {
    }

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """WorkItemSelectApiModelFilter - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            name_or_id (str, none_type): Name or identifier (UUID) of work item. [optional]  # noqa: E501
            include_ids ([str], none_type): Collection of identifiers of work items which need to be included in result regardless of filtering. [optional]  # noqa: E501
            exclude_ids ([str], none_type): Collection of identifiers of work items which need to be excluded from result regardless of filtering. [optional]  # noqa: E501
            project_ids ([str], none_type): Collection of project identifiers. [optional]  # noqa: E501
            name (str, none_type): Name of work item. [optional]  # noqa: E501
            ids ([str], none_type): Specifies a work item unique IDs to search for. [optional]  # noqa: E501
            global_ids ([int], none_type): Collection of global (integer) identifiers. [optional]  # noqa: E501
            attributes ({str: ([str], none_type)}, none_type): Custom attributes of work item. [optional]  # noqa: E501
            is_deleted (bool, none_type): Is result must consist of only actual/deleted work items. [optional]  # noqa: E501
            section_ids ([str], none_type): Collection of section identifiers. [optional]  # noqa: E501
            states ([WorkItemStates], none_type): Collection of states of work item. [optional]  # noqa: E501
            priorities ([WorkItemPriorityModel], none_type): Collection of priorities of work item. [optional]  # noqa: E501
            source_types ([WorkItemSourceTypeModel], none_type): Source type of work item (manual creation or AI generated). [optional]  # noqa: E501
            types ([WorkItemTypeModel], none_type): Collection of types of work item. [optional]  # noqa: E501
            duration (WorkItemFilterApiModelDuration): [optional]  # noqa: E501
            is_automated (bool, none_type): Is result must consist of only manual/automated work items. [optional]  # noqa: E501
            tags ([str], none_type): Collection of tags. [optional]  # noqa: E501
            exclude_tags ([str], none_type): Collection of tags to exclude. [optional]  # noqa: E501
            auto_test_ids ([str], none_type): Collection of identifiers of linked autotests. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        constant_args = {
            '_check_type': _check_type,
            '_path_to_item': _path_to_item,
            '_spec_property_naming': _spec_property_naming,
            '_configuration': _configuration,
            '_visited_composed_classes': self._visited_composed_classes,
        }
        composed_info = validate_get_composed_info(
            constant_args, kwargs, self)
        self._composed_instances = composed_info[0]
        self._var_name_to_model_instances = composed_info[1]
        self._additional_properties_model_instances = composed_info[2]
        discarded_args = composed_info[3]

        for var_name, var_value in kwargs.items():
            if var_name in discarded_args and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self._additional_properties_model_instances:
                # discard variable.
                continue
            setattr(self, var_name, var_value)

        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
        '_composed_instances',
        '_var_name_to_model_instances',
        '_additional_properties_model_instances',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """WorkItemSelectApiModelFilter - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            name_or_id (str, none_type): Name or identifier (UUID) of work item. [optional]  # noqa: E501
            include_ids ([str], none_type): Collection of identifiers of work items which need to be included in result regardless of filtering. [optional]  # noqa: E501
            exclude_ids ([str], none_type): Collection of identifiers of work items which need to be excluded from result regardless of filtering. [optional]  # noqa: E501
            project_ids ([str], none_type): Collection of project identifiers. [optional]  # noqa: E501
            name (str, none_type): Name of work item. [optional]  # noqa: E501
            ids ([str], none_type): Specifies a work item unique IDs to search for. [optional]  # noqa: E501
            global_ids ([int], none_type): Collection of global (integer) identifiers. [optional]  # noqa: E501
            attributes ({str: ([str], none_type)}, none_type): Custom attributes of work item. [optional]  # noqa: E501
            is_deleted (bool, none_type): Is result must consist of only actual/deleted work items. [optional]  # noqa: E501
            section_ids ([str], none_type): Collection of section identifiers. [optional]  # noqa: E501
            states ([WorkItemStates], none_type): Collection of states of work item. [optional]  # noqa: E501
            priorities ([WorkItemPriorityModel], none_type): Collection of priorities of work item. [optional]  # noqa: E501
            source_types ([WorkItemSourceTypeModel], none_type): Source type of work item (manual creation or AI generated). [optional]  # noqa: E501
            types ([WorkItemTypeModel], none_type): Collection of types of work item. [optional]  # noqa: E501
            duration (WorkItemFilterApiModelDuration): [optional]  # noqa: E501
            is_automated (bool, none_type): Is result must consist of only manual/automated work items. [optional]  # noqa: E501
            tags ([str], none_type): Collection of tags. [optional]  # noqa: E501
            exclude_tags ([str], none_type): Collection of tags to exclude. [optional]  # noqa: E501
            auto_test_ids ([str], none_type): Collection of identifiers of linked autotests. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        constant_args = {
            '_check_type': _check_type,
            '_path_to_item': _path_to_item,
            '_spec_property_naming': _spec_property_naming,
            '_configuration': _configuration,
            '_visited_composed_classes': self._visited_composed_classes,
        }
        composed_info = validate_get_composed_info(
            constant_args, kwargs, self)
        self._composed_instances = composed_info[0]
        self._var_name_to_model_instances = composed_info[1]
        self._additional_properties_model_instances = composed_info[2]
        discarded_args = composed_info[3]

        for var_name, var_value in kwargs.items():
            if var_name in discarded_args and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self._additional_properties_model_instances:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")

    @cached_property
    def _composed_schemas():
        # we need this here to make our import statements work
        # we must store _composed_schemas in here so the code is only run
        # when we invoke this method. If we kept this at the class
        # level we would get an error because the class level
        # code would be run when this module is imported, and these composed
        # classes don't exist yet because their module has not finished
        # loading
        lazy_import()
        return {
          'anyOf': [
          ],
          'allOf': [
              WorkItemFilterApiModel,
          ],
          'oneOf': [
          ],
        }
