# flake8: noqa

"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: adapters
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from api_client_adapters.api_client import ApiClient

# import Configuration
from api_client_adapters.configuration import Configuration

# import exceptions
from api_client_adapters.exceptions import OpenApiException
from api_client_adapters.exceptions import ApiAttributeError
from api_client_adapters.exceptions import ApiTypeError
from api_client_adapters.exceptions import ApiValueError
from api_client_adapters.exceptions import ApiKeyError
from api_client_adapters.exceptions import ApiException
