name: Check build like on publish

on:
  - pull_request


permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        package: [
            testit-adapter-behave,
            testit-adapter-nose,
            testit-adapter-pytest,
            testit-adapter-robotframework,
            testit-python-commons
        ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Check version
        run: |
          paths=($(ls | grep 'testit'))
          for str in ${paths[@]}; do
              VERSION=$(grep -oP 'VERSION\s*=\s*"\K[^"]+' $str/setup.py)
              python .version_check/check.py $VERSION
          done
          
      - name: Install dependencies for ${{ matrix.package }}
        working-directory: ${{ matrix.package }}
        run: |
          python -m pip install --upgrade pip
          pip install build
      
      - name: Build package
        working-directory: ${{ matrix.package }}
        run: |
          python -m build -s